#! /usr/bin/env python

import argparse

from configuration import Configuration
from interface import Interfaces
from engine import engine

###############################################################################
def _main():
###############################################################################
    # Grab config info from the various factories

    default_world        = WorldFactory.DEFAULT_WORLD

    parser = argparse.ArgumentParser(description="Play Ba'al!")

    parser.add_argument("-i", "--interface",
                        dest="interface",
                        action="store_const",
                        choices=([str(item) for item in Interfaces]),
                        default="",
                        help="Choose the game interface")

    parser.add_argument("-w", "--world",
                        dest="world",
                        action="store_const",
                        default="",
                        help="Choose the game world. Provide a filename to "
                        "load a world from a file. Provide 'r' to randomly "
                        "generate a world. Provide an integer to select a "
                        "hardcoded world-fixture.")

    parser.add_argument("-p", "--player",
                        dest="player",
                        action="store_const",
                        default="",
                        help="Choose player name")

    args = parser.parse_args()

    # Create and initialize global configuration from args
    Configuration._create(interface_config=args.interface,
                          world_config=args.world,
                          player_config=args.player)

    # Start the game
    engine().play()

if __name__ == "__main__": _main()
