#include "WorldFactoryHardcoded.hpp"
#include "World.hpp"
#include "BaalExceptions.hpp"
#include "Weather.hpp"
#include "Geology.hpp"
#include "City.hpp"

#include <sstream>

namespace baal {

///////////////////////////////////////////////////////////////////////////////
std::shared_ptr<World> WorldFactoryHardcoded::create(const std::string& world_config,
                                                     Engine& engine)
///////////////////////////////////////////////////////////////////////////////
{
  // Convert to int
  unsigned world_id;
  std::istringstream(world_config) >> world_id;

  // Check validity
  RequireUser(world_id > 0 && world_id <= NUM_HARDCODED_WORLDS,
              "Hardcoded world choice " << world_id <<
              " is out of bounds, choose 1-" << NUM_HARDCODED_WORLDS);

  if (world_id == 1) {
    return generate_tiny_world(engine);
  }
  else if (world_id == 2) {
    return generate_scaled_up_tiny(engine);
  }
  else {
    Require(false, "Should never make it here");
  }
}

#define MT(A, B, C, D) std::vector<int> {A, B, C, D}
#define MP(A, B, C, D) std::vector<float>{A, B, C, D}
#define MW(A) std::vector<Wind>(4, A)

///////////////////////////////////////////////////////////////////////////////
std::shared_ptr<World> WorldFactoryHardcoded::generate_tiny_world(Engine& engine)
///////////////////////////////////////////////////////////////////////////////
{
  /*
    This is the world that will be generated:

    T P H M L O
    D D M H L O
    D M H L O O
    H M L L O O
    P L L O O O
    O O O O O O
   */
  static const unsigned ROW = 6;
  static const unsigned COL = 6;

  LocationIterator loc_itr(ROW, COL);

  auto world = std::shared_ptr<World>(new World(ROW, COL, engine));

  std::vector<std::vector<WorldTile*> > tiles = {
    {  // Row 1
      new TundraTile(*loc_itr++,
                     2000,
                     *new Climate(MT(10, 30, 50, 30),
                                  MP(4, 2, .5, 2),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new PlainsTile(*loc_itr++,
                     2500,
                     *new Climate(MT(20, 40, 60, 40),
                                  MP(5, 2.5, 1, 2.5),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(15, 35, 50, 35),
                                 MP(6, 3.5, 2, 3.5),
                                 MW(Wind(15, WSW))),
                    *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(10, 25, 40, 25),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, WSW))),
                       *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(50, 60, 70, 60),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, WSW))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(65, 70, 75, 70),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SW))),
                    *new Subducting(2.0))
    },

    { // Row 2
      new DesertTile(*loc_itr++,
                     2000,
                     *new Climate(MT(25, 50, 75, 50),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     3000,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(12, 27, 42, 27),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, SW))),
                       *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(40, 55, 70, 55),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(15, SW))),
                    *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(52, 62, 72, 62),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, SW))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(67, 72, 77, 72),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SSW))),
                    *new Subducting(2.0))
    },

    { // Row 3
      new DesertTile(*loc_itr++,
                     2500,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, S))),
                     *new Inactive),
      new MountainTile(*loc_itr++,
                       9000,
                       *new Climate(MT(14, 29, 44, 29),
                                    MP(13, 8, 10, 8),
                                    MW(Wind(25, SSW))),
                       *new Inactive),
      new HillsTile(*loc_itr++,
                    4000,
                    *new Climate(MT(42, 57, 72, 57),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(15, SSW))),
                    *new Subducting(3.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(55, 65, 75, 65),
                                MP(9, 9, 9, 9),
                                MW(Wind(10, SSW))),
                   *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Inactive)
    },

    { // Row 4
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(30, 50, 65, 50),
                                 MP(4, 4, 4, 4),
                                 MW(Wind(15, S))),
                    *new Inactive),
      new MountainTile(*loc_itr++,
                       8000,
                       *new Climate(MT(18, 33, 48, 33),
                                    MP(10, 9, 13, 9),
                                    MW(Wind(25, S))),
                       *new Inactive),
      new LushTile(*loc_itr++,
                   1500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Inactive)
    },

    { // Row 5
      new PlainsTile(*loc_itr++,
                     1500,
                     *new Climate(MT(40, 70, 90, 70),
                                  MP(3, 4, 8, 4),
                                  MW(Wind(10, SSE))),
                     *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(57, 67, 77, 67),
                                MP(6, 8, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(59, 69, 79, 69),
                                MP(8, 10, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Subducting(1.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive)
    },

    { // Row 6
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive)
    }
  };

  for (size_t i = 0, ie = tiles.size(); i < ie; ++i) {
    for (size_t j = 0, je = tiles[i].size(); j < je; ++j) {
      world->m_tiles[i][j] = tiles[i][j];
    }
  }

  world->place_city(Location(4, 2), "Capital"); // city

  return world;
}

///////////////////////////////////////////////////////////////////////////////
std::shared_ptr<World> WorldFactoryHardcoded::generate_scaled_up_tiny(Engine& engine)
///////////////////////////////////////////////////////////////////////////////
{
  /*
    This is the world that will be generated:

    T T P P H H M M L L O O
    T T P P H H M M L L O O
    D D D D M M H H L L O O
    D D D D M M H H L L O O
    D D M M H H L L O O O O
    D D M M H H L L O O O O
    H H M M L L L L O O O O
    H H M M L L L L O O O O
    P P L L L L O O O O O O
    P P L L L L O O O O O O
    O O O O O O O O O O O O
    O O O O O O O O O O O O
   */
  static const unsigned ROW = 12;
  static const unsigned COL = 12;

  LocationIterator loc_itr(ROW, COL);

  auto world = std::shared_ptr<World>(new World(ROW, COL, engine));

  std::vector<std::vector<WorldTile*> > tiles = {
    { // Row 1
      new TundraTile(*loc_itr++,
                     2000,
                     *new Climate(MT(10, 30, 50, 30),
                                  MP(4, 2, .5, 2),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new TundraTile(*loc_itr++,
                     2000,
                     *new Climate(MT(10, 30, 50, 30),
                                  MP(4, 2, .5, 2),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new PlainsTile(*loc_itr++,
                     2500,
                     *new Climate(MT(20, 40, 60, 40),
                                  MP(5, 2.5, 1, 2.5),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new PlainsTile(*loc_itr++,
                     2500,
                     *new Climate(MT(20, 40, 60, 40),
                                  MP(5, 2.5, 1, 2.5),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(15, 35, 50, 35),
                                 MP(6, 3.5, 2, 3.5),
                                 MW(Wind(15, WSW))),
                    *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(15, 35, 50, 35),
                                 MP(6, 3.5, 2, 3.5),
                                 MW(Wind(15, WSW))),
                    *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(10, 25, 40, 25),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, WSW))),
                       *new Subducting(2.0)),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(10, 25, 40, 25),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, WSW))),
                       *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(50, 60, 70, 60),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, WSW))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(50, 60, 70, 60),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, WSW))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(65, 70, 75, 70),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SW))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(65, 70, 75, 70),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SW))),
                    *new Subducting(2.0))
    },

    { // Row 2
      new TundraTile(*loc_itr++,
                     2000,
                     *new Climate(MT(10, 30, 50, 30),
                                  MP(4, 2, .5, 2),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new TundraTile(*loc_itr++,
                     2000,
                     *new Climate(MT(10, 30, 50, 30),
                                  MP(4, 2, .5, 2),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new PlainsTile(*loc_itr++,
                     2500,
                     *new Climate(MT(20, 40, 60, 40),
                                  MP(5, 2.5, 1, 2.5),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new PlainsTile(*loc_itr++,
                     2500,
                     *new Climate(MT(20, 40, 60, 40),
                                  MP(5, 2.5, 1, 2.5),
                                  MW(Wind(10, WSW))),
                     *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(15, 35, 50, 35),
                                 MP(6, 3.5, 2, 3.5),
                                 MW(Wind(15, WSW))),
                    *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(15, 35, 50, 35),
                                 MP(6, 3.5, 2, 3.5),
                                 MW(Wind(15, WSW))),
                    *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(10, 25, 40, 25),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, WSW))),
                       *new Subducting(2.0)),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(10, 25, 40, 25),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, WSW))),
                       *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(50, 60, 70, 60),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, WSW))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(50, 60, 70, 60),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, WSW))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(65, 70, 75, 70),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SW))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(65, 70, 75, 70),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SW))),
                    *new Subducting(2.0))
    },

    { // Row 3
      new DesertTile(*loc_itr++,
                     2000,
                     *new Climate(MT(25, 50, 75, 50),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     2000,
                     *new Climate(MT(25, 50, 75, 50),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     3000,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     3000,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(12, 27, 42, 27),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, SW))),
                       *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(12, 27, 42, 27),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, SW))),
                       *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(40, 55, 70, 55),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(15, SW))),
                    *new Subducting(2.0)),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(40, 55, 70, 55),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(15, SW))),
                    *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(52, 62, 72, 62),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, SW))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(52, 62, 72, 62),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, SW))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(67, 72, 77, 72),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SSW))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(67, 72, 77, 72),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SSW))),
                    *new Subducting(2.0))
    },

    { // Row 4
      new DesertTile(*loc_itr++,
                     2000,
                     *new Climate(MT(25, 50, 75, 50),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     2000,
                     *new Climate(MT(25, 50, 75, 50),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     3000,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     3000,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, SW))),
                     *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(12, 27, 42, 27),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, SW))),
                       *new Inactive),
      new MountainTile(*loc_itr++,
                       10000,
                       *new Climate(MT(12, 27, 42, 27),
                                    MP(12, 7, 8, 7),
                                    MW(Wind(25, SW))),
                       *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(40, 55, 70, 55),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(15, SW))),
                    *new Subducting(2.0)),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(40, 55, 70, 55),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(15, SW))),
                    *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(52, 62, 72, 62),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, SW))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(52, 62, 72, 62),
                                MP(8, 8, 8, 8),
                                MW(Wind(10, SW))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(67, 72, 77, 72),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SSW))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(67, 72, 77, 72),
                                 MP(9, 9, 9, 9),
                                 MW(Wind(10, SSW))),
                    *new Subducting(2.0))
    },

    { // Row 5
      new DesertTile(*loc_itr++,
                     2500,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, S))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     2500,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, S))),
                     *new Inactive),
      new MountainTile(*loc_itr++,
                       9000,
                       *new Climate(MT(14, 29, 44, 29),
                                    MP(13, 8, 10, 8),
                                    MW(Wind(25, SSW))),
                       *new Inactive),
      new MountainTile(*loc_itr++,
                       9000,
                       *new Climate(MT(14, 29, 44, 29),
                                    MP(13, 8, 10, 8),
                                    MW(Wind(25, SSW))),
                       *new Inactive),
      new HillsTile(*loc_itr++,
                    4000,
                    *new Climate(MT(42, 57, 72, 57),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(15, SSW))),
                    *new Subducting(3.0)),
      new HillsTile(*loc_itr++,
                    4000,
                    *new Climate(MT(42, 57, 72, 57),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(15, SSW))),
                    *new Subducting(3.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(55, 65, 75, 65),
                                MP(9, 9, 9, 9),
                                MW(Wind(10, SSW))),
                   *new Subducting(3.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(55, 65, 75, 65),
                                MP(9, 9, 9, 9),
                                MW(Wind(10, SSW))),
                   *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Inactive)
    },

    { // Row 6
      new DesertTile(*loc_itr++,
                     2500,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, S))),
                     *new Inactive),
      new DesertTile(*loc_itr++,
                     2500,
                     *new Climate(MT(30, 55, 80, 55),
                                  MP(4, 1.5, 1, 1.5),
                                  MW(Wind(10, S))),
                     *new Inactive),
      new MountainTile(*loc_itr++,
                       9000,
                       *new Climate(MT(14, 29, 44, 29),
                                    MP(13, 8, 10, 8),
                                    MW(Wind(25, SSW))),
                       *new Inactive),
      new MountainTile(*loc_itr++,
                       9000,
                       *new Climate(MT(14, 29, 44, 29),
                                    MP(13, 8, 10, 8),
                                    MW(Wind(25, SSW))),
                       *new Inactive),
      new HillsTile(*loc_itr++,
                    4000,
                    *new Climate(MT(42, 57, 72, 57),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(15, SSW))),
                    *new Subducting(3.0)),
      new HillsTile(*loc_itr++,
                    4000,
                    *new Climate(MT(42, 57, 72, 57),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(15, SSW))),
                    *new Subducting(3.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(55, 65, 75, 65),
                                MP(9, 9, 9, 9),
                                MW(Wind(10, SSW))),
                   *new Subducting(3.0)),
      new LushTile(*loc_itr++,
                   1000,
                   *new Climate(MT(55, 65, 75, 65),
                                MP(9, 9, 9, 9),
                                MW(Wind(10, SSW))),
                   *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Subducting(3.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(70, 75, 80, 75),
                                 MP(10, 10, 10, 10),
                                 MW(Wind(10, S))),
                    *new Inactive)
    },

    { // Row 7
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(30, 50, 65, 50),
                                 MP(4, 4, 4, 4),
                                 MW(Wind(15, S))),
                    *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(30, 50, 65, 50),
                                 MP(4, 4, 4, 4),
                                 MW(Wind(15, S))),
                    *new Inactive),
      new MountainTile(*loc_itr++,
                       8000,
                       *new Climate(MT(18, 33, 48, 33),
                                    MP(10, 9, 13, 9),
                                    MW(Wind(25, S))),
                       *new Inactive),
      new MountainTile(*loc_itr++,
                       8000,
                       *new Climate(MT(18, 33, 48, 33),
                                    MP(10, 9, 13, 9),
                                    MW(Wind(25, S))),
                       *new Inactive),
      new LushTile(*loc_itr++,
                   1500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Inactive)
    },

    { // Row 8
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(30, 50, 65, 50),
                                 MP(4, 4, 4, 4),
                                 MW(Wind(15, S))),
                    *new Inactive),
      new HillsTile(*loc_itr++,
                    5000,
                    *new Climate(MT(30, 50, 65, 50),
                                 MP(4, 4, 4, 4),
                                 MW(Wind(15, S))),
                    *new Inactive),
      new MountainTile(*loc_itr++,
                       8000,
                       *new Climate(MT(18, 33, 48, 33),
                                    MP(10, 9, 13, 9),
                                    MW(Wind(25, S))),
                       *new Inactive),
      new MountainTile(*loc_itr++,
                       8000,
                       *new Climate(MT(18, 33, 48, 33),
                                    MP(10, 9, 13, 9),
                                    MW(Wind(25, S))),
                       *new Inactive),
      new LushTile(*loc_itr++,
                   1500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   1500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(60, 70, 80, 70),
                                MP(8, 10, 12, 10),
                                MW(Wind(10, S))),
                   *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Subducting(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(11, 11, 11, 11),
                                 MW(Wind(10, SSE))),
                    *new Inactive)
    },

    { // Row 9
      new PlainsTile(*loc_itr++,
                     1500,
                     *new Climate(MT(40, 70, 90, 70),
                                  MP(3, 4, 8, 4),
                                  MW(Wind(10, SSE))),
                     *new Transform(2.0)),
      new PlainsTile(*loc_itr++,
                     1500,
                     *new Climate(MT(40, 70, 90, 70),
                                  MP(3, 4, 8, 4),
                                  MW(Wind(10, SSE))),
                     *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(57, 67, 77, 67),
                                MP(6, 8, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(57, 67, 77, 67),
                                MP(6, 8, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(59, 69, 79, 69),
                                MP(8, 10, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(59, 69, 79, 69),
                                MP(8, 10, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Subducting(1.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Subducting(1.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive)
    },

    { // Row 10
      new PlainsTile(*loc_itr++,
                     1500,
                     *new Climate(MT(40, 70, 90, 70),
                                  MP(3, 4, 8, 4),
                                  MW(Wind(10, SSE))),
                     *new Transform(2.0)),
      new PlainsTile(*loc_itr++,
                     1500,
                     *new Climate(MT(40, 70, 90, 70),
                                  MP(3, 4, 8, 4),
                                  MW(Wind(10, SSE))),
                     *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(57, 67, 77, 67),
                                MP(6, 8, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(57, 67, 77, 67),
                                MP(6, 8, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(59, 69, 79, 69),
                                MP(8, 10, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new LushTile(*loc_itr++,
                   500,
                   *new Climate(MT(59, 69, 79, 69),
                                MP(8, 10, 16, 8),
                                MW(Wind(10, SSE))),
                   *new Transform(2.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Subducting(1.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Subducting(1.0)),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(75, 80, 85, 80),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, SE))),
                    *new Inactive)
    },

    { // Row 11
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive)
    },

    { // Row 12
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr++,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive),
      new OceanTile(*loc_itr,
                    1000,
                    *new Climate(MT(80, 85, 90, 85),
                                 MP(12, 12, 12, 12),
                                 MW(Wind(10, ESE))),
                    *new Inactive)
    }
  };

  for (size_t i = 0, ie = tiles.size(); i < ie; ++i) {
    for (size_t j = 0, je = tiles[i].size(); j < je; ++j) {
      world->m_tiles[i][j] = tiles[i][j];
    }
  }

  world->place_city(Location(8, 4), "Capital"); // city

  return world;
}

#undef MT
#undef MP
#undef MW

}
